#!/bin/bash

# Allow aliases to be with sudo
alias sudo="sudo "

# Easier Navigation
alias ~="cd ~"
alias ..="cd .."
alias ...="cd ../.."

# IP Addresses
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias localip="ifconfig | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p'"

# Copy public key
alias pubkey="cat ~/.ssh/id_rsa.pub | pbcopy | printf 'Public key copied to clipboard.\n'"

# Flush Directory Service cache
alias flush="dscacheutil -flushcache && killall -HUP mDNSResponder"

# Alias Chrome
alias chrome='/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome'
alias canary='/Applications/Google\ Chrome\ Canary.app/Contents/MacOS/Google\ Chrome\ Canary'