#!/bin/bash

DOTFILES_DIR="${HOME}/.dotfiles"
source "${HOME}/.dotfiles/shell/load_dotfiles";

# Allow for a local .bash_profile to set machine specific settings
load_local_profile() {
  LOCAL_PROFILE="${HOME}/.bash_profile.local"
  if [[ -r $LOCAL_PROFILE ]]; then
    source $LOCAL_PROFILE
  fi
}

load_local_profile
unset load_local_profile