#!/bin/bash

load_dotfiles() {

  declare -a files=(
    "./shell/colors"
    "./shell/exports"
    "./shell/paths"
    "./shell/aliases"
    "./shell/completion"
    "./shell/prompt"
    "./shell/functions/*"
    # Allow for a local .bash_profile to set machine specific settings
    "${HOME}/.bash_profile.local"
  )

  for file in ${files[@]}
  do
    if [[ -r $file ]]; then
      source $file
    fi
  done

}

load_dotfiles
unset load_dotfiles