#!/bin/bash

if tput setaf 1 &> /dev/null; then
  bold=$(tput bold)
  normal=$(tput sgr0)
  underline=$(tput smul)
  # Display all available colors with tput:
  # for i in {0..255}; do tput setab $i; echo -n " $i "; done; tput setab 0; echo
  black=$(tput setaf 0)
  blue=$(tput setaf 33)
  cyan=$(tput setaf 81)
  green=$(tput setaf 35)
  orange=$(tput setaf 208)
  purple=$(tput setaf 129)
  red=$(tput setaf 196)
  white=$(tput setaf 255)
  yellow=$(tput setaf 220)
else
  bold=""
  normal=""
  underline="\e[4m"
  reset="\e[0m"
  black="\e[30m"
  blue="\e[34m"
  cyan="\e[36m"
  green="\e[32m"
  orange="\e[33m"
  purple="\e[35m"
  red="\e[31m"
  white="\e[37m"
  yellow="\e[33m"
fi