#!/bin/bash

load_files() {

  if [[ -r $(brew --prefix)/etc/profile.d/bash_completion.sh ]]; then
    source $(brew --prefix)/etc/profile.d/bash_completion.sh
  fi

  eval "$(npm completion 2>/dev/null)"

  # Placeholder for other potential completion files
  # declare -a files=(
  #   ""
  # )

  # for file in ${files[@]}
  # do
  #   if [[ -r $file ]]; then
  #     source $file
  #   fi
  # done

}

load_files
unset load_files