#!/bin/bash

declare -a dirs=(
  "/usr/local/bin"
  "/usr/bin"
  "/bin"
  "$HOME/bin"
  "$HOME/.dotfiles/bin"
  "$HOME/.rvm/bin"
)

# Append directories to path
for dir in "${dirs[@]}"; do
  if [[ -d $dir ]]; then
    PATH="$PATH:${dir}"
  fi
done

unset dirs

export PATH