#!/bin/bash

declare -a dirs=(
  "/usr/local/bin"
  "/usr/bin"
  "/bin"
  "$HOME/bin"
  "$HOME/.dotfiles/bin"
  "$HOME/.rvm/bin"
)

# Append directories to path
for index in ${!dirs[*]}
do
  if [ -d ${dirs[$index]} ]; then
    PATH="$PATH:${dirs[$index]}"
  fi
done

unset dirs

export PATH