#!/bin/zsh

DOTFILES_DIR="${HOME}/.dotfiles"
source "${HOME}/.dotfiles/shell/load_dotfiles";

setopt auto_cd              # if not a command and is a directory, auto cd into it
setopt correct              # try to correct the spellings of commands
setopt share_history        # share history with all sessions
setopt hist_ignore_dups     # ignore if the previous command is a duplicate

# Intelligent up/down history
bindkey '^[[A' history-beginning-search-backward
bindkey '^[[B' history-beginning-search-forward

# Allow for a local .bash_profile to set machine specific settings
load_local_profile() {
  LOCAL_PROFILE="${HOME}/.zshrc.local"
  if [[ -r $LOCAL_PROFILE ]]; then
    source $LOCAL_PROFILE
  fi
}

load_local_profile
unset load_local_profile