#!/bin/bash

# Set computer name
#ComputerName="computername"
#sudo scutil --set ComputerName "${ComputerName}"
#sudo scutil --set LocalHostName "${ComputerName}"
#sudo scutil --set HostName "${ComputerName}"
#sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server NetBIOSName -string "${ComputerName}"

# Always show scrollbars
# Possible values: `WhenScrolling`, `Automatic`, and `Always`
defaults write NSGlobalDomain AppleShowScrollBars -string "Always"

# Set dark theme for Yosimite
sudo defaults write /Library/Preferences/.GlobalPreferences AppleInterfaceTheme Dark
defaults write "Apple Global Domain" "AppleInterfaceStyle" "Dark"

# Automatically quit printer app once the print jobs complete
defaults write com.apple.print.PrintingPrefs "Quit When Finished" -bool true

# Disable the "Are you sure you want to open this application?" dialog
defaults write com.apple.LaunchServices LSQuarantine -bool false

# Restart automatically if the computer freezes
sudo systemsetup -setrestartfreeze on

# Expand save panel by default
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode2 -bool true