#!/bin/bash

# Set the icon size of Dock items
defaults write com.apple.dock tilesize -int 44

# Minimize windows into their application’s icon
defaults write com.apple.dock minimize-to-application -bool true

# Show indicator lights for open applications in the Dock
defaults write com.apple.dock show-process-indicators -bool true

# Remove the auto-hiding Dock delay
defaults write com.apple.dock autohide-delay -float 0

# Make Dock icons of hidden applications translucent
defaults write com.apple.dock showhidden -bool true

# Prevent Dock from showing recently opened items
defaults write com.apple.dock show-recents -bool false