#!/bin/bash

run_brew() {

  # Install Homebrew
  # - Need to do a check for Linuxbrew: https://raw.githubusercontent.com/Linuxbrew/install/master/install)
  if ! type_exists 'brew'; then
    printf "${STATUS_COLOR}Installing homebrew... ${CHECKMARK}${RESET}\n"
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  else
    brew update > /dev/null &
    spinner "${STATUS_COLOR}Updating brew...${RESET}"
  fi

  brew bundle install --file ./brew/Brewfile

  # Remove outdated versions from the Cellar
  brew cleanup > /dev/null 2>&1

}