#!/bin/bash

run_git() {

  # Initialize the git repo if it doesn't exist
  if ! git rev-parse --git-dir > /dev/null 2>&1; then
    printf "${STATUS_COLOR}Initializing git repository... ${CHECKMARK}${RESET}\n"
    git init --quiet
    git remote add origin ${DOTFILES_GIT}
    git fetch origin master > /dev/null 2>&1
    # Reset the index and the working try to the fetched HEAD
    git reset --hard HEAD > /dev/null 2>&1
    git clean -df
  fi

  # Sync with the remote repo
  printf "${STATUS_COLOR}Syncing dotfiles... ${CHECKMARK}${RESET}\n"
  git pull --rebase origin master > /dev/null 2>&1
  git log -1 --pretty=format:'%C(white dim)[master]%Creset %C(yellow)%h%Creset %s %C(cyan)(%cr)%Creset %Cgreen<%cn>%Creset'

}