#!/bin/bash

run_npm() {

  if type_exists 'npm'; then

    # List of npm packages
    local -a packages_list=(
      'babel-cli'
      'devtool'
      'english-words-that-are-not-yet-npm-packages'
      'eslint'
      'http-server'
      'n'
      'tslint'
    )
    local packages=$( printf "%s " "${packages_list[@]}" )

    # Install global packages
    npm install $packages --global --silent
    printf "${STATUS_COLOR}Installing npm packages... ${CHECKMARK}${RESET}\n"

  else
    printf "\n"
    echo "Error: npm not found"
    exit
  fi

}