#!/bin/bash

# Check that a given type exists
type_exists() {
  if [ $(type -P $1) ]; then
    return 0
  fi
  return 1
}

# Ask for confirmation
ask_confirmation() {
  printf "$1"
  read -p " (y/n) " -n 1
  printf "\n"
}

# Test whether the result of an 'ask' is a confirmation
is_confirmed() {
  if [[ "$REPLY" =~ ^[Yy]$ ]]; then
    return 0
  fi
  return 1
}

spinner() {
  local pid=$!
  local delay=0.1
  local spin='\|/-'
  local i=0
  while kill -0 $pid 2>/dev/null
  do
    i=$(( (i+1) %4 ))
    printf "\r$1 [${spin:$i:1}]"
    sleep ${delay}
  done
  printf "\r$1 ${CHECKMARK}  \n"
}