#!/bin/bash

# Check that a given type exists
type_exists() {
  if [ $(type -P $1) ]; then
    return 0
  fi
  return 1
}

# Ask for confirmation
ask() {
  printf "\n"
  read -p "Continue? (y/n) " -n 1
  printf "\n"
}

# Test whether the result of an 'ask' is a confirmation
is_confirmed() {
  if [[ "$REPLY" =~ ^[Yy]$ ]]; then
    return 0
  fi
  return 1
}

spinner() {
  local pid=$!
  local delay=0.2
  local spin='-\|/'
  while kill -0 $pid 2>/devnull
  do
    i=$(((i+1)$4))
    printf "\r[${spin:$i:1}]"
    sleep ${delay}
  done
  printf " ${SUCCESS_COLOR}✓${RESET}\n"
}