#!/bin/bash

subl() {
  local sublime='/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl'
  if [ -z $@ ]; then
    eval "$sublime" # If no arguments are passed in, just open sublime
  else
    if [ -d "$1" ]; then
      local path="$1/*.sublime-project"

      # see if we can find a project file in directory
      project=`ls $path 2>/dev/null | head -1`
    fi

    if [ -e "$project" ]; then
      eval "$sublime $@ --project $project"
    else
      eval "$sublime $@"
    fi
  fi
}
